swagger: '2.0'
info:
  description: 'a6s-cloudに関するAPIです。'
  version: 1.0.0
  title: a6s-cloud
host: localhost
basePath: /api/v1
tags:
  - name: AnalysisResults
    description: 解析結果の詳細
  - name: AnalysisResultLists
    description: 解析結果の一覧
  - name: AnalysisRequests
    description: 解析依頼
paths:
  /AnalysisResults/{Id}:
    get:
      summary: "解析結果の詳細API"
      description: "指定されたIdの情報を返します"
      tags:
        - AnalysisResults
      parameters:
      - name: "Id"
        in: "path"
        description: "取得したい解析結果のID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                example: 1
                description: "id"
              analysisWord:
                type: "string"
                example: "#運用ちゃんデプロイイベント"
                description: "解析ワード"
              status:
                type: "integer"
                example: 2
                description: "ステータス(0: 実施前, 1: 実施中, 2: 成功, 3: 失敗, 4: キャンセル)"
              url:
                type: "string"
                example: "http://localhost:8080/analysisResult/10"
                description: "勉強会URL"
              image:
                type: "string"
                example: "d89552e1-e054-440f-b8db-f7c413ed43b8.png"
                description: "画像ファイル"
              favoriteCount:
                type: "integer"
                example: "62"
                description: "いいね総数"
              retweetCount:
                type: "integer"
                example: 8
                description: "リツイート総数"
              tweetCount:
                type: "integer"
                example: 38
                description: "ツイート総数"
              userCount:
                type: "integer"
                example: 21
                description: "ユーザー総数"
              userRanking:
                type: "array"
                description: "ユーザ情報"
                items:
                  type: "object"
                  properties:
                    tweetCount:
                      type: "integer"
                      example: 1
                      description: "ツイート数"
                    userAccount:
                      type: "string"
                      example: "llminatoll"
                      description: "ユーザーアカウント"
                    userName:
                      type: "string"
                      example: "湊川あい🌱書籍版 #運用ちゃん 発売"
                      description: "ユーザー名"
              analysisStartDate:
                type: "string"
                example: "2019-05-09 00:00:00"
                description: "解析開始日"
              analysisEndDate:
                type: "string"
                example: "2019-05-09 23:59:59"
                description: "解析終了日"
              insertDate:
                type: "string"
                example: "2019-05-09 00:59:27"
                description: "登録日付"
              updateDate:
                type: "string"
                example: "2019-05-09 00:59:31"
                description: "更新日時"
              deleteFlag:
                type: "integer"
                example: "0"
                description: "削除フラグ"
  /AnalysisRequests:
    post:
      summary: "解析依頼のAPI"
      description: "検索ワードで解析を行います"
      tags:
        - AnalysisRequests
      parameters:
      - name: "startDate"
        in: "query"
        description: "解析日付:2019/05/10"
        required: true
        type: "string"
      - name: "analysisWord"
        in: "query"
        description: "解析ワード:#運用ちゃんデプロイイベント"
        required: true
        type: "string"
      - name: "url"
        in: "query"
        description: "勉強会URL:aaa.co.jp"
        type: "string"
      - name: "analysisTiming"
        in: "query"
        description: "解析タイミング:[1,2]"
        required: true
        type: "string"
      - name: "autoTweet"
        in: "query"
        description: "自動ツイート:true"
        type: "string"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "string"
            example: 1
            description: "解析結果ID"
